---
- name: Levantar nodos de tor_bridge
  hosts: all
  remote_user: ubuntu
  tasks:
  - name: Mover el archivo torrc_bridge a la máquina.p
    copy:
          src: ../config/torrc_bridge
          dest: /home/ubuntu/torrc_bridge
  - name: Aplicar Script de config del bridge.
    script: ../scripts/install_bridge.sh 
