version: "3"
services:
  middle-node:
    build: ./
    volumes:
      - ./data:/var/lib/tor
      - ./config/torrc:/etc/tor/torrc
    ports:
      - "80:80"
      - "9050:9050"
      - "443:443"
      - "8080:8080"